dist: buster
language: python
services: docker

env:
  global:
    - IMAGE_NAME=jamiehewland/alpine-pypy
    - REGISTRY_USER=jamiehewland
    - secure: "CD4Kt1+/wnPiqNk9a5rQgTYk697ScEnRgrajh65QIDT6QRzCtCaj+tHIPxv/leUcOiNueN6GxWUq2gWv1pxtm5GidMPDAKeYfkB9jyq0GdHu0fhWHKLvBeK9RSbLkFpSxvtJzEdUDLUEHBj89B6PoiBGoHy3H23uz1aPxzuIkC+ZlicZuZi9cku3uTeA7ZkrahWD90lvm4XwsZqvGrutbxTr/PlKZ4lZb/uiYWd9VLIR2kWny0G7eGA9BnuKIoUBXwpbUSOMJPBI3LyY2cr/+04nPq7Dqw6J4YEtvF8S4M61AFPVT2s+QfLIVP2UCvE4uN14loP0hLKu1SF4ylstPh2zL4t+xZopsF1HddJeCVo6qmv5Kl3dCcOwlRllneOhf2igLwBrhXIEFsS4sYjWJSdojPiAQ0UoOy1fYmQfHz61ahlLhIl+Ay6NeaaQrGNHlU+Lx/GhcsG0lO7Ufsm6rcXDgYOCVxmiXug06e9nVsnE/MlhAzgqlzp4vAynqxrgWKANUSxXzTKXjxv0YFVFxnbVfT1M4n3xH/v8zFd+VS8xg3HJSyewhxHWTezRwnp9XIMC0T490ZE70cCtV1zCHeTVyxqPOBUey1WHLNmqT8P4ZkHbCCbw7yZk9Gl/FGzbs743Aw1Y+6kS1kX4Eaa/1HlCS7JBxH2DBXtcQBnErIo="
  matrix:
    - VERSION=2.7/alpine3.11 TAG_LATEST=
    - VERSION=3.6/alpine3.11 TAG_LATEST=1

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - cd "$VERSION"
  - image="$IMAGE_NAME:${VERSION%/*}"
  - version="${VERSION%/*}-$(awk '$2 == "PYPY_VERSION" { print $3; exit }' Dockerfile)"
  - echo "Building image $image with PyPy version $version"
  - docker pull "$image" || true

script:
  - docker build --pull --cache-from "$image" -t "$image" .
  # Run the "official-images" tests, but first tag our image like the official
  # ones to get the same tests
  - |
    official_image="pypy:${VERSION%/*}"
    docker tag "$image" "$official_image"
    ~/official-images/test/run.sh "$official_image"

after_script:
  - docker images

before_deploy:
  - pip install docker-ci-deploy==0.3.0
  - docker login --username "$REGISTRY_USER" --password "$REGISTRY_PASS"
deploy:
  provider: script
  script: dcd -t latest "${VERSION#*/}" -V "$version" -S ${TAG_LATEST:+-L} "$image"
  on:
    branch: master
