dist: buster
language: python
services: docker

env:
  global:
    - IMAGE_NAME=jamiehewland/alpine-pypy
    - REGISTRY_USER=jamiehewland
    - secure: "jCF9Z8/Q2Jft6ngq8MEQREZhGT/JI3daj763N+aZn67ZxLIBsht4hOZJikOMVWCT3OGopAVXkMkQkqLIOm1/vaaa498QLmeAz5BMsiedg5JcKN+mpRlWcoyrlqnuS0bcbcssXEYSu8jYCpd1fT7iDsWbnLazDVpBT8NrPuXWpVsGHs77mpNR5Di2NsnBHwakC5VqDrwx3n7R7shNyfqJ9eJoXr1Lqs7wM02/GbKfGC+KlPpQ/HnLruWvv5mX25vs/j2tPp+TbzBTtMpALysw54PJo+ZP2yonRfPfMvD1KCme3pA3SpGf4yWHLr/JVGTPrpbrMN5dmTYYFRolt6i9BJpfucLLKXu/17XLeVLVvbVptbug7Iux1r1gi6IaFSPiZOpYoltBsuoQeeLed+cd4g9d+M1w0rhTVMNholf2oFb3BLpnNVXRjJck6nw6b06U1m/u2hZ0UjHi2K5OPaJtwAi8pUURArs95bmHJMezzwOu01HQpfBVycFGDMbXVlt6CvaCHOnSi3JCUESl/GxdUmLrIexgFdPUfn104mjbvo5pvpCkKs4C+1qedwXuZoU+fnZfkV6rdfDyHGGhNeJQsh5WlkT0/IBjsYngmGsBnVvxsw5HU4iGomzAOHGHRiaNitBDaU6cHvresEnwu88sDzU9F2tq/yMdEyTIfSyM60g="
  matrix:
    - VERSION=2.7/alpine3.11 TAG_LATEST=
    - VERSION=3.6/alpine3.11 TAG_LATEST=1

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - cd "$VERSION"
  - image="$IMAGE_NAME:${VERSION%/*}"
  - version="${VERSION%/*}-$(awk '$2 == "PYPY_VERSION" { print $3; exit }' Dockerfile)"
  - echo "Building image $image with PyPy version $version"
  - docker pull "$image" || true

script:
  - docker build --pull --cache-from "$image" -t "$image" .
  # Run the "official-images" tests, but first tag our image like the official
  # ones to get the same tests
  - |
    official_image="pypy:${VERSION%/*}"
    docker tag "$image" "$official_image"
    ~/official-images/test/run.sh "$official_image"

after_script:
  - docker images

before_deploy:
  - pip install docker-ci-deploy==0.3.0
  - echo -n "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
deploy:
  provider: script
  script: dcd -t latest "${VERSION#*/}" -V "$version" -S ${TAG_LATEST:+-L} "$image"
  on:
    branch: master
