sudo: required
group: trusty_latest
language: python
services: docker

branches:
  only:
    - master

env:
  global:
    - IMAGE_NAME=jamiehewland/alpine-pypy
    - REGISTRY_USER=jamiehewland
    - secure: "4qDsmFNSiMYOmAsDugOEsTxOJIszKtMUqiymNWsWyNq1MYDRsRzILtfAAxHo1V6Bva2JfCKwQu6PRu53kW6SvgIZhtcVD33qx/fhGGXa4izZO3E2znSLJ2x15iO8Py/4OHkMWEG+y/HLh4sDWhEQEM25mGrcYywc0iBIWnmezQ2yOH2ow3MlMTQ+Eu3vDWmD4CyDJU/fmAx9rU38xzYK1mksiSgjPC0xsM3ZLsbIiEXXhTZzgwJvrBfVaEMosO2ZI3dYeVEe0v0eaMPT9Sh2prQqsNUJrIWQQpzLQB4g/ORUddj96LbJ0lplsJgJ9f86xN0F4wEoc0aEea8tSMjXEnxatQi4nwXRXm0HbC2K4/rMqqTbn5PBi3pMtS4k02lxvysJyaaaMc0cjE4ZiQsSPlYEmxet1gaJbM+PGDCvvTfuPaDTwbWWZLslHkxdriAZhI5pKl2++hjm1/HP88cY1YWOIBW7fW+wawyApATfznPKVzdoyLapHc+hLsVVU/rB8QHTWMEjpLAGVjZpHwYYyidZngbIAnzRxBt0LyJJnHSO5jGgIrtkgJbtwdCgNVaAGCcZ9a+bwQWNuSxPC2d4tLufpqbMEXMujKG3YPyrQ6/80MRqdKa1TBZwwnsOWfjSwZe+7i9wxBz1gR6KegLMOCuMAslcCxA+BoaezH2cbPY="
  matrix:
    - VERSION=2/alpine3.7 TAG_LATEST=
    - VERSION=3/alpine3.7 TAG_LATEST=1

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - cd "$VERSION"
  - image="$IMAGE_NAME:${VERSION%/*}"
  - version="${VERSION%/*}-$(awk '$2 == "PYPY_VERSION" { print $3; exit }' Dockerfile)"
  - echo "Building image $image with PyPy version $version"
  - docker pull "$image" || true

script:
  - docker build --pull --cache-from "$image" -t "$image" .
  # Run the "official-images" tests, but first tag our image like the official
  # ones to get the same tests
  - |
    official_image="pypy:${VERSION%/*}"
    docker tag "$image" "$official_image"
    ~/official-images/test/run.sh "$official_image"

after_script:
  - docker images

before_deploy:
  - pip install docker-ci-deploy==0.3.0
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
deploy:
  provider: script
  script: dcd -t latest "${VERSION#*/}" -V "$version" -S ${TAG_LATEST:+-L} "$image"
  on:
    branch: master
