dist: buster
language: python
services: docker

env:
  global:
    - IMAGE_NAME=jamiehewland/alpine-pypy
    - REGISTRY_USER=jamiehewland
    - secure: "Um5W87ReiBNM3jSeD8ZWceurOcDh56YwcLYZQxiEikBY3Ajka740YO/KfoPj3+T1Gw3dELkhgonMDWHoaPG965l1OQAIURsaKR4Sm/TltJ3Acd5n0xD8d6nkZAZUbBxS8wL3j5pNv63wwq5XGDFeKHbUZQSVwja+T5nbayY5hyLoKEcfHyHdP25obb33ovsx7ctJTkXvXw0tDdqDTWl5DeNUfs6oGeeo+mVdrPRp+eg2t8VK8KmeeYBPmjgiSMawTCFpSCa6r7cn/WHvo3N2SyG7XI2FBWz+1TC0EQ/9TMxAOThflhbjqsOE01qhLxywiXB8cLDSUZa0mg+Vhro+dHmJzgsh8KPOpZsnSNyUTykGm7TxH039tKVz3R9cabGuSqYLS9FS1T5/W0ycimeqZrzT+qcbGY+sUkxjpz8wxYuE0CwuAQglq/k72EUO0zkFOcnPvyDPNZzt7IjPDGvC94/ctlNf9HR7isHcht1qzvb4QfOmB1e1ArH3Yb1VxY8Nbz2wzPnUM1ZzXmT5NKtmgiIaF93fdclUJterffGa3S6Em9Y7MDWNENr/hKEvHfo28arnNLyUPOE5b7rjFaI1hG3MihOShvbIM5/JBhWbRWy1S70Ws/KQXGArUzTxoBvPsEFv5Vn355iY5KqGrj2itr+DSVRimskZI65+IRMiIVM="
  matrix:
    - VERSION=2.7/alpine3.11 TAG_LATEST=
    - VERSION=3.6/alpine3.11 TAG_LATEST=1

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - cd "$VERSION"
  - image="$IMAGE_NAME:${VERSION%/*}"
  - version="${VERSION%/*}-$(awk '$2 == "PYPY_VERSION" { print $3; exit }' Dockerfile)"
  - echo "Building image $image with PyPy version $version"
  - docker pull "$image" || true

script:
  - docker build --pull --cache-from "$image" -t "$image" .
  # Run the "official-images" tests, but first tag our image like the official
  # ones to get the same tests
  - |
    official_image="pypy:${VERSION%/*}"
    docker tag "$image" "$official_image"
    ~/official-images/test/run.sh "$official_image"

after_script:
  - docker images

before_deploy:
  - pip install docker-ci-deploy==0.3.0
  - docker login --username "$REGISTRY_USER" --password "$REGISTRY_PASS"
deploy:
  provider: script
  script: dcd -t latest "${VERSION#*/}" -V "$version" -S ${TAG_LATEST:+-L} "$image"
  on:
    branch: master
